import javax.swing.*;
import java.sql.*;
public class TransactionMenu extends javax.swing.JFrame {
    public TransactionMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountNumber = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        txtField_amount = new javax.swing.JTextField();
        txtField_AccountNumber = new javax.swing.JTextField();
        currentAmount = new javax.swing.JLabel();
        backBTN = new javax.swing.JButton();
        approveBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bankName = new javax.swing.JLabel();
        textField_BankName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNION Bank");
        setPreferredSize(new java.awt.Dimension(780, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        accountNumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountNumber.setText("Recipient Account Number:");
        jPanel1.add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 60));

        amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        amount.setText("Amount (RM):");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 180, 60));

        txtField_amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtField_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 390, 60));

        txtField_AccountNumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtField_AccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 390, 60));

        currentAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(currentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 230, 60));

        backBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 200, 90));

        approveBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        approveBTN.setText("Approve");
        approveBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        approveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBTNActionPerformed(evt);
            }
        });
        jPanel1.add(approveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 200, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/transfer advance.png"))); // NOI18N
        jLabel2.setText("Transfer");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 80));

        bankName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bankName.setText("Bank Name:");
        jPanel1.add(bankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 270, 50));

        textField_BankName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(textField_BankName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 390, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        Sound s = new Sound();
        s.OptionSound();
        OptionMenu om = new OptionMenu();
        om.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void approveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBTNActionPerformed
       V v = new V();
       Sound s = new Sound();
       String loginAcc = v.getName();
       String accNum="";
       String acc = txtField_AccountNumber.getText();
       String amount = txtField_amount.getText();
       String bankName = textField_BankName.getText(); 
       double total = 0;
       double total2 = 0;
       
       if(acc.equals(loginAcc)){
           s.ErrorSound();
           JOptionPane.showMessageDialog(this,"Transaction failed!");
       }else{
       BankFunction BF = new BankFunction();
     if(txtField_AccountNumber.getText().isEmpty()){
         s.ErrorSound();
        JOptionPane.showMessageDialog(this, "Please ensure that your account number is not empty!");       
     }else if(textField_BankName.getText().isEmpty()){
        s.ErrorSound();
        JOptionPane.showMessageDialog(this, "Please ensure that the bank name is not empty!");       
     }else if(txtField_amount.getText().isEmpty()){
        s.ErrorSound();
        JOptionPane.showMessageDialog(this, "Please ensure that the transaction amount is not empty!");
     }else if(Double.parseDouble(txtField_amount.getText())<0) {
         s.ErrorSound();
        JOptionPane.showMessageDialog(this, "Please ensure that the transfer amount valid!");
     }else{
String databaseURL ="jdbc:ucanaccess://src\\database\\Userdb.accdb";  
        try (Connection connection = DriverManager.getConnection(databaseURL)) {
     
               accNum =BF.UNconvertID(connection,loginAcc) ; 
             
           double bal2 = BF.CheckBal(connection,accNum); 
           System.out.println("The amount of "+accNum+" is RM" + bal2);
           double balance = BF.CheckBal(connection,acc); 
           System.out.println("The amount of "+acc+" is RM" + balance);
           total=balance+Double.parseDouble(amount);
           total2=bal2-Double.parseDouble(amount);
           if(!BF.CheckID(connection,acc)){
               s.ErrorSound();
               JOptionPane.showMessageDialog(this,"Invalid account number!");
               TransactionMenu tm = new TransactionMenu();
               tm.setVisible(true);
               this.dispose();
           
           }else if(total2<=0){
            s.ErrorSound();
              JOptionPane.showMessageDialog(this,acc+" current balance is not enought!");
              TransactionMenu tm = new TransactionMenu();
              tm.setVisible(true);
              this.dispose();
                 }else{
           BF.Update(connection,accNum,total2); 
           currentAmount.setText( "RM"+Double.toString(total2));
           System.out.println("The current amount of "+accNum+" is RM" + total2);
           
           BF.Update(connection,acc,total);
           System.out.println("The current amount of "+acc+" is RM" + total);
            
            BF.History(connection,acc,accNum,Double.parseDouble(amount),bankName);
            connection.close();  
            JOptionPane.showMessageDialog(this,"The amount of RM"+amount+" successfully transfer to "+acc+" who the bank name is "+bankName+".\nYour current amount is RM"+total2+".");
            JOptionPane.showMessageDialog(this,"This session will be closed once you clicked OK! \nThank you!");
                 }
        }catch (Exception e){
                System.err.println("Got an exception!");
              
                e.printStackTrace();
                
                System.out.println(e); 
        } 
            OptionMenu om = new OptionMenu();
            om.setVisible(true);
            this.dispose();
     }
       }
       
    }//GEN-LAST:event_approveBTNActionPerformed

    private void moouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moouseClicked
        OptionMenu om = new OptionMenu();
        om.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_moouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel amount;
    private javax.swing.JButton approveBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel bankName;
    private javax.swing.JLabel currentAmount;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textField_BankName;
    private javax.swing.JTextField txtField_AccountNumber;
    private javax.swing.JTextField txtField_amount;
    // End of variables declaration//GEN-END:variables
}
