import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.*;
public class UserProfile extends javax.swing.JFrame {

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        welcome = new javax.swing.JLabel();
        userID = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        accountNumber1 = new javax.swing.JLabel();
        displayName = new javax.swing.JLabel();
        displayUserID1 = new javax.swing.JLabel();
        displayCurrentBalance = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        displayAccNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nextBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nextBTN.setText("Next");
        nextBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });
        jPanel1.add(nextBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 249, 63));

        backBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 244, 66));

        welcome.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome to UNION BANK");
        welcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        welcome.setPreferredSize(new java.awt.Dimension(710, 70));
        jPanel1.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 755, 128));

        userID.setBackground(new java.awt.Color(255, 255, 255));
        userID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userID.setText("User ID:");
        userID.setOpaque(true);
        jPanel1.add(userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 152, 238, 105));

        accountNumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountNumber.setText("Current Balance:");
        jPanel1.add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 447, 221, 111));

        accountNumber1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountNumber1.setText("Account Number:");
        jPanel1.add(accountNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 354, 235, 93));

        displayName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(displayName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 300, 51));

        displayUserID1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayUserID1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(displayUserID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 187, 300, 50));

        displayCurrentBalance.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayCurrentBalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayCurrentBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                displayCurrentBalanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                displayCurrentBalanceMouseReleased(evt);
            }
        });
        jPanel1.add(displayCurrentBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 300, 50));

        name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        name.setText("Name:");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 270, 204, 54));

        displayAccNum.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        displayAccNum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(displayAccNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 300, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                .addGap(1102, 1102, 1102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addContainerGap())
        );

        V v = new V();
        String logAcc = v.getName();
        System.out.println(logAcc);
        String databaseURL = "jdbc:ucanaccess://C:\\Users\\User\\Documents\\NetBeansProjects\\UNION BANK SYSTEM\\src\\database\\Userdb.accdb";
        try (Connection connection = DriverManager.getConnection(databaseURL)) {
            String sqlUser = "select * from User where UserName = ? ";
            PreparedStatement us = connection.prepareStatement(sqlUser);
            us.setString(1,logAcc);
            ResultSet resultUser = us.executeQuery();
            if(resultUser.next()){
                String acc=resultUser.getString("accountNumber");
                String Name=resultUser.getString("Name");
                System.out.println(acc);
                displayUserID1.setText(logAcc);
                displayAccNum.setText(acc);
                displayName.setText(Name);
                displayCurrentBalance.setText("RM****.**");
            }
            connection.close();
        }catch (Exception e){
            System.err.println("Got an exception!");

            e.printStackTrace();

            System.out.println(e);
        }

        setSize(new java.awt.Dimension(780, 710));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        Sound s = new Sound();
        s.OptionSound();
        LoginMenu lm = new LoginMenu();
        lm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
       Sound s = new Sound();
       s.LoginSound();
       OptionMenu om = new OptionMenu();
       om.setVisible(true);
       this.dispose();

    }//GEN-LAST:event_nextBTNActionPerformed

    private void displayCurrentBalanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayCurrentBalanceMousePressed
        //String databaseURL = "jdbc:ucanaccess://C:\\Users\\User\\Documents\\NetBeansProjects\\UNION BANK SYSTEM\\src\\database\\Userdb.accdb";
        BankFunction BF = new BankFunction();
        String databaseURL = "jdbc:ucanaccess://src\\database\\Userdb.accdb";
        String acc = displayAccNum.getText();
        
         try (Connection connection = DriverManager.getConnection(databaseURL)) {
            String sqlBal = "select * from Account where accountNumber = ? ";
            PreparedStatement usBal = connection.prepareStatement(sqlBal);
            usBal.setString(1,acc);
            ResultSet resultBal = usBal.executeQuery();
            if(resultBal.next()){
            double bal=resultBal.getDouble("balance");
            System.out.println(bal);
            displayCurrentBalance.setText("RM"+(BF.decimalFormat(bal)));
        
            }
                 connection.close();  
                }catch (Exception e){
                System.err.println("Got an exception!");
              
                e.printStackTrace();
                
                System.out.println(e); 
               
                }
      
    }//GEN-LAST:event_displayCurrentBalanceMousePressed

    private void displayCurrentBalanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayCurrentBalanceMouseReleased
       displayCurrentBalance.setText("RM****.**");
    }//GEN-LAST:event_displayCurrentBalanceMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel accountNumber1;
    private javax.swing.JButton backBTN;
    private javax.swing.JLabel displayAccNum;
    private javax.swing.JLabel displayCurrentBalance;
    private javax.swing.JLabel displayName;
    private javax.swing.JLabel displayUserID1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JButton nextBTN;
    private javax.swing.JLabel userID;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
