
import java.sql.*;
import javax.swing.*;

public class WithdrawMenu extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawMenu
     */
    public WithdrawMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userID1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        approveBTN = new javax.swing.JButton();
        backBTN = new javax.swing.JButton();
        withdraw = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        checkAccountBTN = new javax.swing.JButton();
        txtField_amount = new javax.swing.JTextField();
        txtField_AccountNumber = new javax.swing.JTextField();
        currentAmount = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        userID1.setText("User ID");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNION BANK");
        setPreferredSize(new java.awt.Dimension(780, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 710));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        approveBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        approveBTN.setText("Approve");
        approveBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        approveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBTNActionPerformed(evt);
            }
        });
        jPanel1.add(approveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, 200, 80));

        backBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backBTN.setText("Back");
        backBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });
        jPanel1.add(backBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 200, 80));

        withdraw.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/withdrawal advance.png"))); // NOI18N
        withdraw.setText("Withdrawal");
        withdraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WithdrawMenu.this.mouseClicked(evt);
            }
        });
        jPanel1.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 290, 70));

        amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        amount.setText("Amount (RM) :");
        jPanel1.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 220, 80));

        accountNumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        accountNumber.setText("Account Number :");
        jPanel1.add(accountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 250, 70));

        checkAccountBTN.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkAccountBTN.setText("Check Balance");
        checkAccountBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        checkAccountBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAccountBTNActionPerformed(evt);
            }
        });
        jPanel1.add(checkAccountBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 200, 80));

        txtField_amount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtField_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 430, 80));

        txtField_AccountNumber.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jPanel1.add(txtField_AccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 430, 80));

        currentAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        currentAmount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(currentAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 430, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Current Balance :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 250, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAccountBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAccountBTNActionPerformed
        Sound s = new Sound();
        BankFunction BF = new BankFunction();
        if(txtField_AccountNumber.getText().isEmpty()){
          s.ErrorSound(); 
          JOptionPane.showMessageDialog(this,"The account number should not be empty!");
        }
     String accNum=txtField_AccountNumber.getText();
        //String databaseURL = "jdbc:ucanaccess://C:\\Users\\User\\Documents\\NetBeansProjects\\UNION BANK SYSTEM\\src\\database\\Userdb.accdb";
        String databaseURL = "jdbc:ucanaccess://src\\database\\Userdb.accdb";
        try (Connection connection = DriverManager.getConnection(databaseURL)) {
            
                String sql = "select * from Account WHERE accountNumber = ? ";
                PreparedStatement us = connection.prepareStatement(sql);                
                us.setString(1,accNum); 
                ResultSet result = us.executeQuery();
                    while(result.next()){
                        double bal=result.getDouble("balance");
                        String acc=result.getString("accountNumber");
                        
                    currentAmount.setText("RM"+ BF.decimalFormat((bal)));
                    System.out.println("The amount for "+acc+" is: RM"+BF.decimalFormat(bal));                          
                }
                 connection.close();  
                }catch (Exception e){
                System.err.println("Got an exception!");
              
                e.printStackTrace();
                
                System.out.println(e); 
                }
    }//GEN-LAST:event_checkAccountBTNActionPerformed

    private void approveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBTNActionPerformed
       Sound s = new Sound();
       String acc = txtField_AccountNumber.getText();
       String amtStr=txtField_amount.getText();
       BankFunction BF = new BankFunction();
       double total = 0;
        String bankName = "UNION Bank";
        String login = "Admin";
      // String databaseURL = "jdbc:ucanaccess://C:\\Users\\User\\Documents\\NetBeansProjects\\UNION BANK SYSTEM\\src\\database\\Userdb.accdb";
       String databaseURL = "jdbc:ucanaccess://src\\database\\Userdb.accdb";
        if(acc.isEmpty()){
            s.ErrorSound();
           JOptionPane.showMessageDialog(this, "Please ensure that your account number should not be blank!");
        }else if(amtStr.isEmpty()){
            s.ErrorSound();
            JOptionPane.showMessageDialog(this, "Please ensure that your withdrawal amount should not be blank!");
        }else if(Double.parseDouble(amtStr)<0){
            s.ErrorSound();
            JOptionPane.showMessageDialog(this, "Invalid withdrawal amount!");
        }else {
            s.SuccessSound();
            double amount=Double.parseDouble(amtStr);
            try (Connection connection = DriverManager.getConnection(databaseURL)) {
                if(!BF.CheckID(connection,acc)){
                 s.ErrorSound();
                JOptionPane.showMessageDialog(this,"Invalid account number!\nPlease try again!");
                WithdrawMenu tm = new WithdrawMenu();
                 tm.setVisible(true);
                this.dispose();
                }else if(BF.CheckID(connection,acc)){
                double bal=BF.CheckBal(connection,acc);
                total=bal-Double.parseDouble(amtStr);
                    if(total<0){
                        s.ErrorSound();
                        JOptionPane.showMessageDialog(this,"The current amount of"+acc+" is not enought!");
                        WithdrawMenu tm = new WithdrawMenu();
                        tm.setVisible(true);
                        this.dispose();
                    }else{
                    BF.Update(connection,acc,total);
                    JOptionPane.showMessageDialog(this,"The current amount of "+acc+" is RM" + total+".");
                    JOptionPane.showMessageDialog(this,"If you want to enter another deposit, please click the WITHDRAWAL button again.");
                    BF.Insert(connection,login,acc,Double.parseDouble(amtStr),bankName);
                    OptionMenu om = new OptionMenu();
                    om.setVisible(true);
                    this.dispose();
                    connection.close();
                    s.SuccessSound();
                    }
                }
            }catch (Exception e){
                    System.err.println("Got an exception!");

                    e.printStackTrace();

                    System.out.println(e); 
            }
        }
       
    }//GEN-LAST:event_approveBTNActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        Sound s = new Sound();
        s.OptionSound();
        OptionMenu om = new OptionMenu();
        om.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNActionPerformed

    private void mouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseClicked
        Sound s = new Sound();
        s.OptionSound();
        OptionMenu om = new OptionMenu();
        om.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JLabel amount;
    private javax.swing.JButton approveBTN;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton checkAccountBTN;
    private javax.swing.JLabel currentAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtField_AccountNumber;
    private javax.swing.JTextField txtField_amount;
    private javax.swing.JLabel userID1;
    private javax.swing.JLabel withdraw;
    // End of variables declaration//GEN-END:variables
}
